version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.3
    restart: always
    ports:
      - 27017:27017
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    ports:
      - 6379:6379
  api:
    container_name: api
    build:
      context: server
      dockerfile: .docker/api/Dockerfile
    command: npm run start:prod
    ports:
      - 4000:4000
